baseURL = 'http://HirofumiTsuda.github.io/blog/'
languageCode = 'en-us'
title = 'Diary and Notes: Hirofumi Tsuda'


[params]
title = "Coffee, Codes, Mathematics and Heavy Metal"
author = "Hirofumi Tsuda"
description = "A warehouse of my thoughts, ideas and studies"
profilePicture = "assets/images/profile/profile.jpeg"

[params.math]
enable = false
use = "mathjax"

[[params.socialIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/hirofumitsuda23/"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "All Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"


  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"



[taxonomies]
    tag = "tags"
    category = "categories"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
